name: pdfarranger
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build-win32:
    runs-on: ubuntu-latest
    container:
      image: jeromerobert/wine-mingw64:1.8.1
      options: --user root
    steps:
    - uses: actions/checkout@v3
    - run: ./setup.py build
    - run: HOME=/root wine python setup_win32.py bdist_msi
    - run: HOME=/root wine python setup_win32.py bdist_zip
    - uses: actions/upload-artifact@v3
      with:
        name: pdfarranger-windows-installer-msi
        path: dist/*.msi
    - uses: actions/upload-artifact@v3
      with:
        name: pdfarranger-windows-portable-zip
        path: dist/*.zip
