name: pdfarranger
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build-win32:
    runs-on: ubuntu-latest
    container:
      image: jeromerobert/wine-mingw64:1.8.1
      options: --user root
    steps:
    - run: apk add py3-pip git
    - uses: actions/checkout@v3
    - run: env
    - run: pip install --upgrade setuptools
    - run: HOME=/root ./setup.py build -v
    - run: find build
    - run: HOME=/root ./setup.py build_i18n -v
    - run: find build
