name: pdfarranger
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build-win32:
    runs-on: ubuntu-latest
    container:
      image: jeromerobert/wine-mingw64:1.8.1
      options: --user root
    steps:
    - uses: actions/checkout@v3
    - run: ./setup.py build -v
    - run: find build
