name: pdfarranger
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build-win32:
    runs-on: ubuntu-latest
    container:
      image: jeromerobert/wine-mingw64:1.8.1
      options: --user root
    steps:
    - uses: actions/checkout@v3
    - run: apk del py3-distutils-extra
    - run: cp cmd.py /usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py && ./setup.py build -v
    - run: find build
    - run: cp cmd.py /usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py && ./setup.py build_i18n -v
    - run: find build
